# Numpy Basic

## Numpy 개요
넘파이는 고성능 수치계산을 위한 라이브러리이다.  
ndarray는 다차원 배열이다. 

**Numpy 로 하는 일**
* List 자료로 Numpy array 로 만들기
* 행렬 형태 확인하기
* 행렬 형태 바꾸기
* 행렬 데이터 만들기
* 행렬의 일부 구간 추출하기
* 행렬끼리 더하기, 곱하기, 행렬 원소간의 연산
* 행렬끼리 합치기
* 그외 연산

In [1]:
import numpy as np  # Make numpy available using np

### ndarray의 생성
* np.array()로 다차원 배열을 생성할 수 있다.
* np.append() - 생성된 배열에 원소(element)를 추가한다.
* 다차원 배열의 원소는 index를 통해 접근할 수 있다.

In [2]:
# Create a numpy array, and append an element
a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: {}".format(a))
print("Printing each element")
for i in a:
    print(i)

print("\nPrinting each element and their index")
for i,e in enumerate(a):
    print("Index: {}, was: {}".format(i, e))

Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


### 수학 함수의 사용
* universal function - 다차원 배열에 일반적인 수학 함수를 적용할 수 있다.

In [3]:
print("\nShowing some basic math on arrays")
b = np.array([0,1,4,3,2])
print("Max: {}".format(np.max(b)))
print("Average: {}".format(np.average(b)))
print("Max index: {}".format(np.argmax(b)))


Showing some basic math on arrays
Max: 4
Average: 2.0
Max index: 2


In [4]:
print("\nYou can print the type of anything")
print("Type of b: {}, type of b[0]: {}".format(type(b), type(b[0])))


You can print the type of anything
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int32'>


## data type

array의 dtype을 본다. 

In [5]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [6]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [7]:
arr = arr.astype(np.int32)
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
arr = np.array([[1., 2, 3], [1, 2, 3]], dtype=np.uint8)
arr.dtype

dtype('uint8')

### ndarray의 차원 확인
len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [9]:
len(arr.shape)

2

In [10]:
arr.shape

(2, 3)

size 확인

In [11]:
arr.size

6

dtype 확인

In [12]:
arr.dtype

dtype('uint8')

## Reshape

ndarray의 형태를 변경한다.

In [13]:
# 행렬의 형태 변경하기
c = [[1,2,3],[4,5,6]]

C = np.array(c)

print('Numpy array C: \n', C)
print('Shape of C :', C.shape)

C = C.reshape(3,2)
print('Numpy array C (reshaped to (3,2)): \n', C)   

Numpy array C: 
 [[1 2 3]
 [4 5 6]]
Shape of C : (2, 3)
Numpy array C (reshaped to (3,2)): 
 [[1 2]
 [3 4]
 [5 6]]


In [14]:
C_colvector = C.reshape(-1,1)   # 행의 크기는 미정이지만 열의 크기는 1로 고정하겠다는 표현입니다.
C_colvector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
print(arr)
print(arr.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


Reshape 

In [16]:
arr = arr.reshape([1, 6])
arr.shape

(1, 6)

In [17]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [18]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [19]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [20]:
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

### random array 생성
* np.random.randint : 균일 분포의 정수 난수 생성
* np.random.rand : 0부터 1사이의 균일 분포에서 난수 배열 생성
* np.random.randn : 가우시안 표준 정규 분포에서 난수 배열 생성

In [21]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [22]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [23]:
arr = arr.reshape(-1, 4, 4)
arr.shape

(4, 4, 4)

In [24]:
arr

array([[[ 1.41645542,  0.1453502 ,  1.31290611,  0.9164397 ],
        [-2.12976254,  1.18659453,  0.73983998,  0.88887438],
        [ 0.25595505, -0.70630121,  0.26199799, -0.42693557],
        [ 0.4268292 , -1.02130285, -0.09652009, -1.15670295]],

       [[-0.42221152,  0.66906981,  1.7685894 , -0.34127902],
        [-1.90404195,  0.1218231 ,  1.04169686, -0.47005479],
        [ 1.19025742, -1.27157764,  0.17999375,  0.56005606],
        [ 1.25486171,  1.50854898, -2.01740917, -0.29087224]],

       [[ 1.29552808,  0.56598165, -0.10219016, -0.88111578],
        [-2.23711808,  0.41989644, -0.3272832 ,  0.97366897],
        [-1.21100945, -0.79006464,  0.57125096,  0.57377871],
        [ 1.11874421,  0.40705545,  0.42508134,  1.25465206]],

       [[ 0.32368954,  1.00604518,  0.05384761,  1.38884127],
        [-0.40363698,  0.67169569, -0.59000511,  1.19148053],
        [-0.87145961,  1.23730851,  1.04693825,  0.8076058 ],
        [ 0.62956279,  1.19924005, -1.8948151 ,  0.85290819]]])

## Ravel
arr의 차원을 1로 변경한다.

In [25]:
arr.shape

(4, 4, 4)

In [26]:
arr = arr.ravel()
arr.shape

(64,)

ravel은 arr.reshape(-1) 와 같다

In [27]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

배열의 값은 유지하되 차원 수를 늘리고 싶을 때가 있다. 
이럴 때 손쉽게 차원을 변경할때 활용되는 것이 expand_dims 함수이다.

In [28]:
arr.shape

(64,)

In [29]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [30]:
arr = arr.ravel()

In [31]:
arr.shape

(64,)

In [32]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)

In [33]:
arr.shape

(1, 64, 1)

## 특정값으로 초기화된 배열의 생성 

* np.zeros() : 0으로 초기화된 배열의 생성
* np.ones() : 1로 초기화된 배열의 생성
* np.arange() : 정수 일렬번호로 초기화된 배열의 생성

0으로 채워진 numpy array를 만들 수 있음

In [34]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
zeros = np.zeros(1)
zeros

array([0.])

In [36]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [38]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [39]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [40]:
arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 배열의 조회 - Indexing

In [42]:
nums = [1, 2, 3, 4, 5]

In [43]:
nums[2:]

[3, 4, 5]

In [44]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [45]:
nums[4]

[1, 2, 3]

In [46]:
arr[1][2]

5

In [47]:
arr[1, 2]

5

## 배열 Slicing

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [50]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

In [51]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Boolean Indexing

In [52]:
data = np.random.randn(3, 3)
data

array([[ 0.98402659, -0.20927682,  0.13073257],
       [ 1.12193198, -0.2340369 ,  0.88349116],
       [ 1.1581458 ,  0.06015592,  0.50482061]])

In [53]:
data <= 0

array([[False,  True, False],
       [False,  True, False],
       [False, False, False]])

In [54]:
data[data <= 0] = 1

In [55]:
data

array([[0.98402659, 1.        , 0.13073257],
       [1.12193198, 1.        , 0.88349116],
       [1.1581458 , 0.06015592, 0.50482061]])

### Broadcasting

브로드캐스팅은 모양이 다른 배열끼리의 연산도 가능하게 해주며 모양이 부족한 부분은 확장하여 연산을 수행할 수 있도록 한다.

In [56]:
import numpy as np

In [57]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [60]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## 배열의 연산,  Math Function

In [62]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [63]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [64]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [65]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [68]:
np.random.seed(0) 
arr = np.random.randint(2, size=27).reshape(3, 3, 3)  # 랜덤 정수로 초기화된 배열의 생성
arr_2 = np.random.randint(2, size=9).reshape(3, 3) # 랜덤 정수로 초기화된 배열의 생성

In [69]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [70]:
arr + arr_2 # 브로드캐스팅을 통한 연산

array([[[1, 2, 1],
        [1, 1, 2],
        [1, 2, 2]],

       [[2, 2, 0],
        [1, 1, 1],
        [0, 1, 1]],

       [[1, 2, 0],
        [2, 1, 1],
        [0, 2, 2]]])

In [71]:
arr * arr_2

array([[[0, 1, 0],
        [0, 0, 1],
        [0, 1, 1]],

       [[1, 1, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [1, 0, 0],
        [0, 1, 1]]])

In [72]:
np.sum(arr)

15

In [73]:
np.sum(arr + arr_2)

33

In [74]:
arr + arr_2

array([[[1, 2, 1],
        [1, 1, 2],
        [1, 2, 2]],

       [[2, 2, 0],
        [1, 1, 1],
        [0, 1, 1]],

       [[1, 2, 0],
        [2, 1, 1],
        [0, 2, 2]]])

In [75]:
(arr + arr_2).shape

(3, 3, 3)

In [76]:
np.max(arr + arr_2)

2

In [77]:
np.min(arr + arr_2)

0

In [78]:
np.max(arr + arr_2, axis=-1) # axis = -1 은 이 경우 axis=2와 동일하다.

array([[2, 2, 2],
       [2, 1, 1],
       [2, 2, 2]])

In [79]:
np.sum(arr + arr_2, axis=-1)

array([[4, 4, 5],
       [4, 3, 2],
       [3, 4, 4]])

In [80]:
np.mean(arr)

0.5555555555555556

* np.argmax() : 배열에서 최대값의 index를 리턴
* np.argmin() : 배열에서 최소값의 index를 리턴

In [81]:
arr = np.array([1, 6, 3, 7, 3, 2, 9, 0, 2])
arr

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

In [82]:
np.argmax(arr)

6

In [83]:
np.argmin(arr)

7

np.unique() - 이 함수는 입력된 배열에서 중복되지 않는 고유한 요소들의 배열을 리턴한다.
* return_counts = True - 중복 되지 않는 요소들의 개수를 리턴한다.

In [84]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [85]:
np.unique(arr) 

array([1, 3, 5, 6])

In [86]:
np.unique(arr, return_counts=True)  

(array([1, 3, 5, 6]), array([1, 3, 1, 2], dtype=int64))

### 행렬의 기본연산

In [87]:
E = np.arange(1,7).reshape(2,3);
print(E)
print(E + 1)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]


In [88]:
E + E

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [89]:
F = np.array([1,2]).reshape(-1,1) 
E * F   #  E 의 첫 행에는 1을 곱하고 두 번쨰 행에는 2를 곱한 결과을 얻습니다.

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [90]:
H = np.array([1,0,1]).reshape(-1,1)
print(E)
print(H)

[[1 2 3]
 [4 5 6]]
[[1]
 [0]
 [1]]


In [91]:
E.dot(H)  

array([[ 4],
       [10]])

## 배열의 연결
* np.hstack() : 배열을 수평방향으로 연결한다.
* np.vstack() : 배열을 수직방향으로 연결한다.

In [92]:
np.hstack((E,E))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [93]:
np.vstack((E,E))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])