# 배열 생성 루틴 연습문제
---

## Ones and zeros

In [3]:
import numpy as np

2*2 integers 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [5]:
np.empty([2,2])

array([[1.08997737e-311, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

X = np.array([1,2,3], [4,5,6], np.int32) 일 때,
X와 동일한 shape를 가지는 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [6]:
X = np.array([[1,2,3], [4,5,6]], np.int32)

np.empty_like(X)

array([[538976288, 538976288, 539767899],
       [170679605, 538976288, 538976288]])

크기가 3인 단위행렬을 생성하세요.

In [44]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

모든 원소가 1로 채워진 3*2 실수형 다차원 배열을 생성하세요.

In [12]:
np.full((3,2),1)

array([[1, 1],
       [1, 1],
       [1, 1]])

x = np.arange(4, dtype=np.int64) 일 때,
X와 동일한 shape를 가지고 모든 원소가 1인 다차원 배열을 생성하세요.

In [13]:
x = np.arange(4, dtype=np.int64)
np.full_like(x,1)

array([1, 1, 1, 1], dtype=int64)

모든 원소가 0으로 채워진 3*2 실수형 다차원 배열을 생성하세요.

In [15]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

x = np.arange(4, dtype=np.int64) 일 때,

x와 동일한 shape의 영행렬을 생성하세요.

In [28]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

모든 원소가 6으로 채워진 2*5 uint형(부호없는 정수) 다차원 배열을 생성하세요.

In [33]:
np.full((2,5), 6, dtype=np.uint8)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint8)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

x = np.arange(4, dtype=np.int64)일 때,

x와 동일한 shape이고 모든 원소가 6인 다차원 배열을 생성하세요.

In [34]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

array([6, 6, 6, 6])

## From existing data

[1, 2, 3] 배열을 생성하세요

In [35]:
np.array([1,2,3])

array([1, 2, 3])

x = [1, 2] 일 때(python list 상태)

x를 배열로 변환하세요.

In [36]:
x = [1,2]
np.array(x)

array([1, 2])

In [0]:
# 다른 솔루션
np.asarray(x)

array([1, 2])

x = [1, 2] 일 때(python list 상태)

x를 `float`형 배열로 변환하세요.

In [37]:
x = [1, 2]
np.array(x, dtype=np.float)

array([1., 2.])

In [0]:
# 다른 솔루션
np.asarray(x, float)

array([1., 2.])

In [0]:
# 다른 솔루션
np.asfarray(x)

array([1., 2.])

## Numerical ranges

2, 4, 6, 8, ..., 100 을 원소로 가지는 배열을 생성하세요.

In [39]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

3.0 에서 10.0 까지 50개의 원소가 균일하게 분포된 1차원 배열을 생성하세요.

In [43]:
np.random.uniform(3.,10.,50)

array([4.65518331, 3.92931058, 7.21067   , 4.94484786, 4.81732488,
       4.81598227, 3.9178482 , 9.26053239, 9.18988986, 6.76948872,
       9.88505992, 5.30774039, 5.80241771, 9.31410764, 3.83460571,
       3.94128945, 7.19580243, 8.0092911 , 7.24748806, 6.92569858,
       6.58582428, 6.64500863, 3.0448965 , 7.52370364, 8.73362609,
       9.50566116, 5.3581481 , 5.95283002, 6.49783046, 7.46926427,
       8.00899162, 4.4742967 , 9.3366495 , 6.99855997, 9.17074843,
       4.61674988, 8.30433366, 8.70729702, 5.71291088, 4.44458522,
       5.75588613, 4.05396229, 5.52929205, 8.58766765, 4.66629091,
       9.34120221, 8.47221504, 8.02384752, 7.76458394, 5.64831926])